### PR TITLE
Implement "assign_attributes" method in "WithAttributes" module

### PR DESCRIPTION
**Pull request by Fabien-Wecasa**
I propose this new method for mass assignment. I have taken the code from [active_model/attribute_assignment.rb](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/attribute_assignment.rb), and adapted it to use Ruby only methods.

### CODE REVIEW

**Comment by rikas** [comment]
@Fabien-Wecasa I get the removal of `transform_keys`, but the `WithAttributes#assign_attributes` is not even being used, I don't get it.

**Comment by Fabien-Wecasa** [comment]
@rikas Thanks for your feedback !
The new method `assign_attributes` is intended to be called from outside the gem. It is a method similar to [the Rails ActiveRecord one](https://apidock.com/rails/ActiveRecord/Base/assign_attributes). It allows to set several attributes at the same time instead of calling several setters. Here is an example of use for a subclass of `BaseRecord` (`class Zoho::Lead < ZohoHub::BaseRecord`):

```
lead = Zoho::Lead.find_by(email: "test@mail.com")
lead.assign_attributes(first_name: "John", last_name: "Doe", mobile: "123456", city: "Paris")
lead.save
```
I use it e.g. for attributes factorization. If I have a hash
```
zoho_lead_attributes = {
  company: "#{first_name} #{last_name}",
  street: "#{street_number} #{street_name}",
  country: "France",
  phone: landline_phone.try { |phone| phone.gsub(/^0/, '+33') },
  mobile: mobile_phone.try { |phone| phone.gsub(/^0/, '+33') },
  ...
}
```
I can call `lead.assign_attributes(zoho_lead_attributes)`.

I've defined this method in `WithAttributes` because it seemed the best place, it is where the setters are defined. Do you think it would be better to define it in `BaseRecord` ?

**Comment by rikas** [comment]
@Fabien-Wecasa I think it makes sense.

I would just remove the prefixing `_` from the private methods, as we have not used that convention anywhere (and I don't really like it :P)

**Comment by Fabien-Wecasa** [comment]
I agree, the `_` prefix is not a very pretty convention :smile: 
I've removed it.

**Comment by rikas** [comment]
Thanks!

**Pull request merged**
